server:
  port: 8081
config:
  arcface-sdk:
    sdk-lib-path: C:\face-recognition\libs
    app-id: 5aE6sqVSpFbcvHZdkJqirnZHyMiG4cNHFdSsAmiqtxsT
    sdk-key: EG4ibBBwcUBHqAMEMHA2vEj6qJChLfwyaAdtkxTqx5eH
    active-key: 86L1-11AD-D12X-XY81
    detect-pool-size: 5
    compare-pool-size: 5
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.143:3306/hf_hotline_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      #????
      pool-name: DateHikariCP
      #???????
      minimum-idle: 5
      # ?????????????600000?10???
      idle-timeout: 180000
      # ????????????10
      maximum-pool-size: 10
      # ?????????????????????,????true
      auto-commit: true
      # ??????????????????0???????????1800000?30??
      max-lifetime: 1800000
      # ?????????,??30???30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#logging:
#  level:
#    com.hfits.facerecognition.face.mapper: debug